### ISSUE TITLE
Is .csv.z an acceptable variant?

### ISSUE THREAD

**Issue by Julian-O** [secretGeek/csvz#4]
If I take a single csv file, and then zip it to end up with a .csv.z, is it conformant with the basic standard, or must the file end with a .csvz extension?

**Comment by secretGeek** [comment]
Hard to see what someone would gain from sticking a “complies with csvz-0 badge” on a .csv.z file, or what a new tool could do with a .csv.z file that couldn’t be done better with an existing csv tool and a zip/unzip tool. 

I guess if someone wanted to flag ahead of time “this thing really only has the one file” it’s better off named .csv.z than .csvz. 

I can’t see the benefit much myself yet. Thoughts?

**Comment by Julian-O** [comment]
Sounds like I am not yet seeing the bigger vision of what the new tool will accomplish. I will close, and look forward to it clicking later.

**Comment by secretGeek** [comment]
Reopening this as I thought of more ways this is useful. 

1. It matches expectation of single file zip so that’s good
2. It signals that there is only 1 csv file, so that’s good
3. Maybe it can have a _meta directory describing that 1 file. 

(But is that allowed in a .z file? To have a directory and other files?)

**Comment by doekman** [comment]
gzip≠zip, or at least see issue #3

**Comment by Julian-O** [comment]
@doekman: Could you please elaborate? I think we all know that, so what triggered your comment? Is there something here that conflates the two?

**Comment by doekman** [comment]
I'm no zip-expert, but I thought zip as in `unzip` on macOS. A zip-file is a widely accepted distribution format. So when I saw gzip, then I thought: that's not it.

But then I saw issue #3 and thought: when that's explicitly defined, this issue might be made irrelevant.

Sorry for my brevity. Does this make my point clear?

**Comment by Julian-O** [comment]
@doekman: I suspect you and I have some different hidden assumption, and I am not sure what it is, because I am nodding along as I read your explanation but not seeing how it ties to this issue.

>  I thought zip as in unzip on macOS

Sure.

> So when I saw gzip, then I thought: that's not it.

Agreed.  that it is a different format. But where did you see gzip? It isn't mentioned in this issue.

> But then I saw issue #3 and thought: when that's explicitly defined, this issue might be made irrelevant.

There is an issue that seems to be being explored elsewhere that the original .Z format only accepts a single file, so @secretGeek's plans to include multiple files in a .Z file may be in trouble. He may need to specify another zip format instead. He may need to specify a .csv.tar.Z format.

But that still leaves the question of whether .csv.Z (or csv.zip) is conformant with the .csvz format, which is what this issue is discussing.

**Comment by secretGeek** [comment]
Ok good explanation and inputs. 

Maybe I’ll close this issue and link it to a new issue called something like:

“How can a .tar.z file full of csvs fit into the csvz specs?” 

As .tar.z can be easily “mapped” to the .csvz standard, whereas a “.csv.z” file can’t be.  (And I think I’m satisfied in that now) 

And because it’s linked, this discussion is not lost, and little insights from it can be easily pulled out and used. 

I’m really enjoying this by the way, thank you very much to both of you!!

**Comment by secretGeek** [comment]
Hence closing this issue: 

Answer:

a .csv.z file can’t comply. 

But the good news is:

a csvz.tar.z can comply!

... once issue #20 is resolved. 

(And it might prefer an extension of .csvz.tz or something)
Fun fun!!
